In [ ]:
######################## Reading Data from .yaml file ############################
##################################################################################

In [46]:
from sensor.utils.main_utils import read_yaml_file

In [47]:
file_path="C:/Users/jatpradh/Documents/Proj_iNeuron/07_Sensor_Project/sensor-fault-detection/config/schema.yaml"

In [48]:
schema_config = read_yaml_file(file_path=file_path)

In [50]:
len(schema_config['columns'])

164

In [ ]:
######################## Drifting ############################
##############################################################

In [2]:
from scipy.stats import ks_2samp

In [3]:
import numpy as np

In [11]:
d1 = np.arange(10)
d2 = np.arange(10)

In [12]:
d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
test = ks_2samp(d1,d2)

In [15]:
test.pvalue

1.0

In [23]:
# The above scenario belongs to the same distribution .

In [16]:
d1 = np.arange(100,200)
d2 = np.arange(10)

In [17]:
d1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [18]:
d2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
ks_2samp(d1,d2)

KstestResult(statistic=1.0, pvalue=4.2646072253826637e-14)

In [19]:
test = ks_2samp(d1,d2)

In [20]:
test.pvalue

4.2646072253826637e-14

In [21]:
round(test.pvalue)

0

In [ ]:
# p-value < 0.05 , reject the NULL hypothesis . So data are not of same distribution .

In [25]:
traing_file_path = "C:/Users/jatpradh/Documents/Proj_iNeuron/07_Sensor_Project/sensor-fault-detection/artifact/11_03_2022_09_03_06/data_ingestion/ingested/train.csv"

In [26]:
test_file_path = "C:/Users/jatpradh/Documents/Proj_iNeuron/07_Sensor_Project/sensor-fault-detection/artifact/11_03_2022_09_03_06/data_ingestion/ingested/test.csv"

In [27]:
import pandas as pd

In [28]:
train_df = pd.read_csv(traing_file_path)
test_df = pd.read_csv(test_file_path)

In [29]:
train_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [30]:
test_df.columns

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [32]:
d1 = train_df['aa_000']
d2  = test_df['aa_000']
ks_2samp(d1,d2)

KstestResult(statistic=0.007858321260228118, pvalue=0.8768306597905058)

In [ ]:
# p-value > 0.05 , Accept the NULL hypothesis . So data are of same distribution .

In [33]:
d1 = train_df['class']
d2  = test_df['class']
ks_2samp(d1,d2)

KstestResult(statistic=0.003217938253718855, pvalue=0.9999999912830789)

In [34]:
# p-value > 0.05 , Accept the NULL hypothesis . So data are of same distribution .

In [ ]:
#Now do it for every column - To find the data drifts

In [35]:
columns = list(train_df.columns)

In [36]:
d1 = train_df['class']
d2  = test_df['class']
ks_2samp(d1,d2)

KstestResult(statistic=0.003217938253718855, pvalue=0.9999999912830789)

In [ ]:
# For all columns -2

In [37]:
def get_drift_report(base_df,current_df,threshold=0.05):
    report ={}
    for column in base_df.columns:
        d1 = base_df[column]
        d2  = current_df[column]
        is_same_dist = ks_2samp(d1,d2)
        if threshold<=is_same_dist.pvalue:
            is_found=False
        else:
            is_found = True 
        report.update({column:{
            "p_value":float(is_same_dist.pvalue),
            "drift_status":is_found
            
            }})
    return report

In [38]:
drift_report = get_drift_report(train_df,test_df)

In [39]:
drift_report

{'class': {'p_value': 0.9999999912830789, 'drift_status': False},
 'aa_000': {'p_value': 0.8768306597905058, 'drift_status': False},
 'ab_000': {'p_value': 0.9999007671615837, 'drift_status': False},
 'ac_000': {'p_value': 0.9503144337017586, 'drift_status': False},
 'ad_000': {'p_value': 0.8813649366776779, 'drift_status': False},
 'ae_000': {'p_value': 0.9986571726562143, 'drift_status': False},
 'af_000': {'p_value': 0.9959643069937159, 'drift_status': False},
 'ag_000': {'p_value': 1.0, 'drift_status': False},
 'ag_001': {'p_value': 0.9987532082366527, 'drift_status': False},
 'ag_002': {'p_value': 0.9326228061418614, 'drift_status': False},
 'ag_003': {'p_value': 0.9163655451274716, 'drift_status': False},
 'ag_004': {'p_value': 0.349868660740847, 'drift_status': False},
 'ag_005': {'p_value': 0.45413832648726893, 'drift_status': False},
 'ag_006': {'p_value': 0.841348320289216, 'drift_status': False},
 'ag_007': {'p_value': 0.5706718891342062, 'drift_status': False},
 'ag_008': {

In [41]:
# Export the report to .yaml file

In [42]:
from sensor.utils.main_utils import write_yaml_file

In [43]:
drift_report = get_drift_report(train_df,test_df)

In [44]:
import os

In [45]:
write_yaml_file(file_path=os.path.join(os.getcwd(),"Handle_Data-Drift_report.yaml"),content=drift_report,replace=True)

In [ ]:
################################ Target Value Mapping ############################
##################################################################################

In [1]:
from sensor.ml.model.estimator import TargetValueMapping

In [3]:
TargetValueMapping().to_dict()

{'neg': 0, 'pos': 1}

In [4]:
TargetValueMapping().reverse_mapping()

{0: 'neg', 1: 'pos'}